### ISSUE TITLE
Some symbols show "NEW_TO_2525D" Tag but don't look new

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#135]
While putting together a list of new Line/Area symbols - I came across numerous entries that don't look like they should be considered new. They should have the 2525C tag fixed and should also show up in the LegacyCtoD table:

These were just a few I noticed (not an exhaustive list):

Maneuver Lines : Forward Edge of the Battle Area : Proposed or On Order	Control Measure : Line	25140401
Maneuver Lines : Direction of Attack : Friendly Planned or On Order	Control Measure : Line	25140604
Maneuver Lines : Direction of Attack : Enemy Confirmed	Control Measure : Line	25140606
Maneuver Lines : Direction of Attack : Enemy Templated or Suspected	Control Measure : Line	25140607
Maneuver Areas : Axis of Advance : Supporting Attack Planned or On Order	Control Measure : Line	25151405
Maneuver Areas : Axis of Advance : Enemy Confirmed	Control Measure : Line	25151407
Maneuver Areas : Axis of Advance : Enemy Templated or Suspected	Control Measure : Line	25151408
Maneuver Areas : Proposed or On Order Assembly Area	Control Measure : Area	25150400
Maneuver Areas : Encirclement : Enemy	Control Measure : Area	25151802

**Comment by abouffard** [comment]
These are, in fact, new symbols in 2525D.  They are not new in terms of what they represent, but they are new in terms of the way they represent information.

They are also redundant, being an oversight and the result of some confusion between the Army and DISA. They all use an entity type or entity subtype code to define information about standard identity and/or status, and are therefore redundant because standard identity and status are also represented in codes in the first ten digits of their SIDCs.  Allowing two methods for codifying standard identity and status is dangerous at worst and inconsistent/confusing at best.

Esri has authored a change proposal (https://github.com/Esri/joint-military-symbology-xml/blob/master/documentation/change_proposals/CP_Esri_021115-1.doc) to eliminate these control measures, and several others like them, from 2525D Change 1.  Like any CP, once approved by the SSMC/JSP they become effective/implementable immediately.  When/if this new CP gets approved, these affected control measures, and the others like them, will be removed from JMSML.

**Comment by csmoore** [comment]
So, just to confirm - these can't possibly be mapped to a 2525C IDs?

**Comment by ottenw** [comment]
@abouffard Very happy to see this CP ... fixing this identified error was on my list of change proposals to write.  Thanks!

**Comment by wmcgrane** [comment]
DISA is reviewing this request and it has been given the CP tracking number of 15-022-DS (meaning:  submitted in Year 2015, #22 in the queue, sponsored by DISA).  If accepted by DISA as a valid request, it will then be distributed to the Services and Agencies for symbology for comment and those finding presented at the joint JSP/SSMC meeting 16-20 March 2015 for the CCB's consideration into 2525D change 1.  Once approved, the specifications in the CP are effective immediately upon approval date.


Bill McGrane
Chair, Symbology Standards Management Committee
DISA EE212
Messaging Standards Section
Ft. Meade, MD
301-225-7383




-----Original Message-----

**Comment by abouffard** [comment]
@csmoore, the original issue here was that I'd used the NEW_TO_2525D tag on these and you were pointing out, rightly so, that they didn't look new.  I think I've adequately explained why they don't look new but in fact are new.  The policy here with JMSML is that symbols that are new to 2525D, by definition, don't map back to 2525C, because the mapping would not end up being bi-directional.  You've raised a second question here, though, which is indeed valid, should a system, like JMSML or a system implementing the standards, map these particular 2525D SIDCs back to something "similar" or "familiar" in 2525C, and I think that belongs more with the discussion that goes along with issue #124.  If a symbol is new in 2525D, and its SIDC is received by a 2525C-compatible system, should that system be able to display it as something similar or familiar, or should it just treat it as a bad symbol/object?  Definitely something we'll be discussing at next month's SSMC/JSP meeting.  I would hope this won't really be a huge issue with the control measures documented in my referenced CP, because few systems have implemented 2525D yet.  So, with any luck, we can get the CP approved and delete these errant control measures before they become widely used.

@ottenw, thank you sir.  Happy to oblige and save you the effort. :-)

@wmcgrane, thanks for this information.  Did you want your contact details to be part of your comment above?  Sending to GitHub from a mail application will send EVERYTHING, including your signature and any included/quoted messages.  I have taken the liberty of deleting the quoted part of your comment and can remove your contact details too, if you wish.

**Comment by csmoore** [comment]
I was originally just asking for the 2525C tag to be added to those - but closing since sounds like this is a "wont fix" (at least as far as 2525D.0 is concerned).

Also sounds like it is becoming more of a global issue that there is a need to clarify the interoperability requirements between systems using 2525C and 2525D (I don't yet see an open CP for this [here](https://github.com/Esri/joint-military-symbology-xml/tree/master/documentation/change_proposals) ).
