### ISSUE TITLE
Land Unit SectorOne Modifier Addition and color correction for 10751.svg

### ISSUE THREAD

**Issue by JKCowboy** [Esri/joint-military-symbology-xml#170]
I created a pull request https://github.com/Esri/joint-military-symbology-xml/pull/168 that should provide the solution to these two issues (my first, so hopefully it is correct).

1) Land Equipment does not have a reference to "Not Applicable" SectorOne Modifier ("00"). This change adds this so tools can display this for drop downs, etc.

2) 10751.svg used a blue color to display the SectorOne Modifier (medical cross). This change makes it black.

**Comment by abouffard** [comment]
Thanks @JKCowboy.  I fixed the blue cross in 10751.svg.  As I explained in my comment to #168, I don't want to change the land equipment modifier list at this time, as adding a not applicable value would have to be considered for all the modifiers and I'm not convinced the XML needs to hold that information.  Its something we'll discuss at the next SSMC meeting in March.

**Comment by joebayles** [comment]
@abouffard @JKCowboy the current Esri implementation for 2525D starts the modifier list at 01, so 00 isn't an option on the list. This is detrimental in two ways:

 1. If ArcGIS is set up to consume SIDC codes (which it currently isn't, only set up for coded domain values), it will most likely throw an error when it sees extra 00s that have been truncated in the system.
 2. If ArcGIS is set up to export SIDC codes, it currently would not include 00s, and could conceivably send 6 digits instead of 10.

We need to add 00 as an option.

**Comment by joebayles** [comment]
Additionally, @abouffard should submit a CP to the SSMC to update the Modifier 1 and 2 tables with the verbiage they want ("Unspecified" vs. "Not Applicable"), and the appendices with the 00 values (currently, they start at 01).

**Comment by abouffard** [comment]
Closing this as 00 modifiers have been added to the v.next branch and successfully tested with Military Features Data.
