### ISSUE TITLE
Static/Dynamic control measures question

### ISSUE THREAD

**Issue by kjellmf** [Esri/joint-military-symbology-xml#174]
In the official 2525D PDF you find that many control measures have a Static/Dynamic or Shape/Size attribute. I assume that static means that the control measure is a single point, while a dynamic one consists of multiple points/segments etc. 

![image](https://cloud.githubusercontent.com/assets/29217/6416842/6bf451e6-bea9-11e4-84b9-bba8c3fdc279.png)

In the JMSML schema I can't find any static/dynamic data attribute. Is it instead represented by the 
`GeometryType`attribute? Should I interpret  `GeometryType= POINT` as a static control measure?

**Comment by abouffard** [comment]
Good question @kjellmf .  I'd like to see what @mepler and @wmcgrane have to say regarding the definition of static vs. dynamic in the control measure documentation.  We have plans to add more geometric/draw rule intelligence to the XML, so this information will probably be better captured that way.

**Comment by kjellmf** [comment]
I'm trying to figure out how to draw control measures on a map (web.application).  For point geometries I can use the SVGs bundled with JMSML directly. Line and area control measures are a lot harder to draw. More meta data in the XML, like for instance anchor points, will  hopefully make this easier.

**Comment by abouffard** [comment]
Yup, that's the idea.  Our own implementation has all those anchor points defined and maintained externally.  I'd like to see them centralized inside JMSML so that all implementers are working from a common definition of these.  Same goal for label placement logic/rules.

**Comment by wmcgrane** [comment]
All:

Yes, these terms should be more accurately defined in order to avoid any misinterpretation and incorrect usage.  The definitions currently in the standard are as follows:
Paragraph 3.2.14.  Dynamic amplifier.  An amplifier whose size and placement are based on the attributes of an object and can change as these attributes and the scale of the background change.
Paragraph 3.2.41.  Static amplifier. An amplifier whose size and placement are fixed and remain constant.

When 2525 was first developed, its focus was primarily focused on surface (land and sea) and non-surface (sub and air) objects and their movements/direction of movements.  For example:
 Paragraph 5.3.6.12.3 states that "...the static direction of movement amplifier is a fixed length and identifies only the direction of movement of the object."

In every appendix is this definition of a text amplifier:  "The purpose of the static text amplifiers described in the appendix is to standardize the display of additional alphanumerical information on identity, movement and location and capabilities."
Likewise, there is a definition of a graphic amplifier:  "Graphic amplifiers can be static, located in a fixed position in relation to a track’s symbol, or dynamic and move about the symbol based on the track’s characteristics."

However, when we get into the Command and Control, METOC, and Cyber appendices, we do not see these definitions spelled out as clearly.  Theoretically, it could be deduced that the application of those terms used in these appendices have the same meaning and function.  But I do agree that it might be a good idea to make those definitions explicit in all appendices, or perhaps define them more broadly in the base document, thus eliminating the necessity of having to replicate identical definitions in every appendix.  Indeed, better geometric/draw rule intelligence will help to improve the implementation and rendering of the symbols.

Thus is the SSMC chair's opinion. But the definitive answer will be determined by the SSMC members, as I have no vote (except in a tie)   :-)

Regards,

Bill McGrane
Chair, Symbology Standards Management Committee
DISA EE212
Messaging Standards Section
Ft. Meade, MD
301-225-7383

-----Original Message-----

**Comment by ottenw** [comment]
Classification: UNCLASSIFIED
Caveats: NONE
Good Afternoon Everyone,

  My two cents worth - as I believe that control measure symbols are a bit challenging due to their complexity and variety.  As the original words in this thread stated "...the definition of static vs. dynamic in the control measure documentation", I thought I would first research the older versions of MIL-STD-2525 to see the origin and whether or not the usage has changed over time.  I found that the term "Static/Dynamic" appears first in MIL-STD-2525B (January 1999), in section B.5.4.  Interesting in that while it specifically states "The Static/Dynamic column indicates whether the tactical graphic's size is fixed or changes in proportion with the background projection", the actual column in Table B-IV is titled "Fixed/Dynamic".

  For the purpose of clarifying static vs. dynamic in the draw rules for MIL-STD-2525D Control Measure Symbols, I would offer the following.


1.     The words Static/Dynamic need to be removed from the draw rules for individual symbols.  If these words are needed, then they should be defined up front one time rather than being repeated over and over in the 255 pages of Appendix H.

2.     With regards to lines and areas, I would offer that any symbol containing two or more points is dynamic, as it will change depending on the point location, distance between points, and the number of points.

3.     That leaves only single point symbols.  A single point symbol could be considered static if the single point control measure's "... size is fixed ... in proportion with the background projection".  But is this something that should be defined within the standard, or left up to an implementer of the standard?  If a system operator changes the map/image background for example from a 1:50,000 topographic line map (TLM) to a 1:250,000 scale Joint Operational Graphic (JOG) map, should the size of the single point control measures be unchanged / fixed / static, should they scale proportionally in relation to the updated map or image background and become 5X smaller and perhaps unrecognizable, or should that be left to the system implementer as a user defined display preference?

4.     If the definition of the words Static/Dynamic are changed/added, I would suggest not including the word "projection" in the definition.  Projection has a very specific meaning in the geospatial world, and its inclusion in MIL-STD-2525 could cause more confusion than clarification.

  Bill McGrane, time permitting, next week's SSMC meeting could be a good forum/time to discuss this topic / issue.

  Have a great day.

V/R,

Bill Otten

Senior Professional Systems Engineer
PM Mission Command TMD / PD FSC2
SETA contractor support (CSC)

PM Mission Command Field Office
106 Wynn Drive
2D300-B2
Huntsville, AL 35805-1957
256-842-1948
BB: 443-243-9777
william.r.otten.ctr@mail.mil
Please consider the environment before printing this email

**Comment by kjellmf** [comment]
Thank you for the clarification regarding dynamic vs static control measures. From the comments I conclude that I can interpret entities with  `GeometryType="POINT"` (default value) as static and other values as dynamic.

**Comment by wmcgrane** [comment]
Bill Otten:
Thank you for your input.  I could make the time to discuss by turning this into a CP and adding it to the list for discussion.  That thought had crossed my mind, so if I get the opportunity this week, I will draft a CP sponsored by DISA, and with your permission, I will use the language you've stated below as part of the CP.


Bill McGrane
Chair, Symbology Standards Management Committee
DISA EE212
Messaging Standards Section
Ft. Meade, MD
301-225-7383



-----Original Message-----

**Comment by wmcgrane** [comment]
Thanks.

-----Original Message-----

**Comment by kjellmf** [comment]
Closing this now that the meeting is over and I got my answer.

**Comment by abouffard** [comment]
We ran out of time this week in the SSMC/JSP meeting to have an in-depth discussion regarding the terms static and dynamic and their usage within the standards.  I think a comprehensive review of the control measure symbols and the way they are presented in the document will be part of the ongoing development of 2525D Change 1 and APP-6(D).
