### ISSUE TITLE
Wavy Line Weather/METOC Symbols do not display curves in Desktop/Runtime Export

### ISSUE THREAD

**Issue by jrweakland** [Esri/joint-military-symbology-xml#184]
_From @csmoore on February 7, 2014 2:11_

Lines with curved effect do not display in Desktop or Runtime Dictionary.GetSymbolImage (they were working with MessageProcessor on Map though)

Marginal Visual Flight Rule (MVFR),WA-DBAMV----A-- (Mil2525C) 
W*A*FV----*****	Visual Ceiling (APP6B)

As a workaround, the Curved Effect has been removed from the Representation Rule until this issue is addressed in Desktop (10.3+).  Now draws with straight blue line, should draw like:

![curvyweather](https://f.cloud.github.com/assets/3090809/2106091/3da99676-8f9c-11e3-916d-138c7b0abbe2.png)

_Copied from original issue: Esri/military-features-data#12_

**Comment by wmcgrane** [comment]
Jim:
Was the Curved Effect a capability that was available in 2525 Charlie but now not functional in 2525 Delta?
Or is it due to a Desktop/Runtime Export issue?

In other words, is the problem with the standard or with the program?

Regards,

Bill McGrane
Chair, Symbology Standards Management Committee
DISA EE212
Messaging Standards Section
Ft. Meade, MD
301-225-7383


 

-----Original Message-----

**Comment by csmoore** [comment]
This is an issue with this actual ArcGIS Style/implementation (so should probably be moved back to the other repo).

Note: this is still an issue with the polygon symbol in current 2525D style/x.

![image](https://cloud.githubusercontent.com/assets/3090809/7586823/d815b694-f87e-11e4-9776-ce5c816c9f46.png)

Left (from standard/SVG) - Right (in 2525D in ArcGIS Pro)

**Comment by jrweakland** [comment]
This issue was moved to Esri/military-features-data#65
