### ISSUE TITLE
Add Additional domain exports (ex. Context and Land_Unit_Special_Entity_Subtype)

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#200]
Please add these additional/missing domain exports to 
https://github.com/Esri/joint-military-symbology-xml/tree/master/samples/name_domains_values

For more information on where these domains are referenced in the standard, please see 2525D Table VII and TABLE D-II.

`*` - recall that each domain file has the convention of Coded_Domain_{domain}.csv

- [x] Context `*`

Name	Value
Reality	0
Exercise	1
Simulation	2

- [x] Land_Unit_Special_Entity_Subtype

Name	Value
Headquarters Element	95
Division and Below Support	96
Corps Support	97
Theater/Echelons Above Corps Support	98

- [x] SIGINTMobility

Mobile M
Static S
Uncertain U

- [x] Reinforced

```
+	0
-	1
+/-	2
```

- [x] Credibility

Confirmed By Other Sources	1
Probably True	2
Possibly True	3
Doubtfully True	4
Improbable	5
Truth Cannot Be Judged	6

- [x] Reliability 

Completely Reliable	A
Usually Reliable	B
Fairly Reliable	C
Not Usually Reliable	D
Unreliable	E
Reliability Cannot Be Judged	F

- [x] CombatEffectiveness

Fully Operational	FO
Substantially Operational	SO
Marginally Operational	MO
Not Operational	NO
Unknown	UNK

- [x] Status 

0=P=Present
1=A=Planned/Anticipated/Suspect

**Comment by csmoore** [comment]
Note: the original issue has just been added to/updated to add additional domains that were found in the geodatabase we use (after these were cross checked against the 2525D standard tables Table VII and D-II)

**Comment by abouffard** [comment]
@csmoore , the context domain values are already here: https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/symbolcode_firstten_domains_values/jmsml_Context.csv

Do we still need the contents of https://github.com/Esri/joint-military-symbology-xml/tree/master/samples/symbolcode_firstten_domains_values, as we are relying on the files in https://github.com/Esri/joint-military-symbology-xml/tree/master/samples/name_domains_values for building the actual domain ranges?

Do we need to add to https://github.com/Esri/joint-military-symbology-xml/tree/master/samples/name_domains_values as I implement the enhancements in this issue to add the new domain range outputs to the other folder?

IMHO there is too much redundancy between https://github.com/Esri/joint-military-symbology-xml/tree/master/samples/name_domains_values and https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/symbolcode_firstten_domains_values and we should just do away with https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/symbolcode_firstten_domains_values.  That older folder was useful once when we just wanted a simple list of the values, but I think the newer folder now satisfies our requirement for a set of comprehensive domain range files (comprehensive once this issue is implemented and closed)..

**Comment by csmoore** [comment]
Once you have the gdb-automated-creation working feel free to optimize the samples/exports. 

The original goal of those exports/samples (>=1.5 years ago) was just to demonstrate producing some simple/representative output.

**Comment by abouffard** [comment]
Regarding status above...

Status
0=P=Present
1=A=Planned/Anticipated/Suspect

I'm not sure what is being inferred by "P" and "A" here, as the standard format of our domain exports is "Name, Value", i.e. two columns, not three columns.  Were three columns actually required in this export or was the "P" and "A" just added for clarity?

"P" and "A" as one letter codes within a 15 character SIDC are part of the 2525C SIDC specification.  Those particular codes are not part of 2525D, and therefore not explicitly defined in JMSML.

**Comment by csmoore** [comment]
I was similarly confused - but that is how they were described in "TABLE H-I" "H.5.1.1.3 Status." when we went over this together - so included for completeness, perhaps that should be CP'd if unclear or a cobweb left over from 2525C.

**Comment by abouffard** [comment]
Yes, I think those are vestiges of 2525C and an administrative change proposal should probably address cleaning those up.  No similar mention is made to A and P in the main body of the document, where Status is also discussed.

**Comment by abouffard** [comment]
@wmcgrane, the CP in question is probably not necessary.  We're just recommending an administrative change that would remove mention of "P" and "A", because those letter codes don't make sense now, since we no longer have an alphabetic SIDC to use them in.

**Comment by wmcgrane** [comment]
Got it.  Thanks,

Bill McGrane
Chair, Symbology Standards Management Committee
DISA BDC/EE212
Messaging Standards Section
Ft. Meade, MD
301-225-7383



-----Original Message-----

**Comment by abouffard** [comment]
Completed with PR #212, #213, #214, and #215 

@csmoore , please verify and close.

Thank you.

**Comment by csmoore** [comment]
Checked - only issue I noticed was name, value appear reversed for context: https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/name_domains_values/Coded_Domain_Context.csv

This can be closed after that is fixed

**Comment by abouffard** [comment]
Fixed the context export in #216.  Also updated the copyright dates on all C# source.

@csmoore , please review and close/comment as appropriate.

**Comment by csmoore** [comment]
Verified - we'll also need to test this data against the domain import steps at https://github.com/Esri/military-features-data/blob/master/data/mil2525d/utilities/military-features-utilities/README.md#steps (and remove that workaround from those steps) - I'll add a task for you to do this, so you can be familiar with this process (so you can apply this same general process to the field creation)
