### ISSUE TITLE
Redundant Dummies in MIL-STD-2525D ?

### ISSUE THREAD

**Issue by ottenw** [Esri/joint-military-symbology-xml#224]
I am finalizing a MIL-STD-2525D change proposal for submission to the SSMC to fix the Minefield control measure symbols.  Specifically, replace the "A" amplifier with a new Mine Type graphic amplifier.  I also was working to define draw rules for the "Dummy" portion of the Dummy Minefield and Dummy Minefield, Dynamic symbols,  While completing this, I noticed that the alignment of two parts in the template and example of the Decoy/Dummy control measure symbols are different.  Second, the Decoy/Dummy and Decoy/Dummy/Feint control measures systems are identical despite having unique SIDCs.  Third, there is a Feint/Dummy Indicator, amplifier "AB", a graphic amplifier that is applicable to units, equipment, installations, and activities.  Forth, and perhaps most significant given the building block approach to symbology in MIL-STD-2525D, look at SIDC set A position 8 "HQ / Task Force / Dummy.  If the use of this digit in the SIDC is legal / authorized for all symbols in all appendixes' in MIL-STD-2525D, then amplifier "AB" is redundant, and control measure symbols "Dummy  Minefield", "Dummy Minefield, Dynamic", "Decoy/Dummy", and "Decoy/Dummy/Feint" are all redundant and a CP is needed to delete them from MIL-STD-2525D.  Thoughts?

**Comment by csmoore** [comment]
Not repeating attributes (Planned, Hostile, Dummy) in the Entity Code that are already captured elsewhere (and could conflict) sounds like a (globally) good idea to me:

![image](https://cloud.githubusercontent.com/assets/3090809/10099584/f0e646da-6358-11e5-981a-1eef42f97e8f.png)

You may want to still leave the image examples in the standard (with the full/corrected code) in case someone is looking for them by name: 

As an implementer - I am a little concerned about the solution mentioned - adding an extra attribute "mine type" attribute that will be required to create the correct symbol. We can do this but it will create an exceptional/odd case (i.e. be the only symbol graphic that can't be derived from the SIDC alone, and will increase the messaging complexity). Using a mine type attribute was a continual problem in 2525B/MOLE explaining to users the need to do this and what to set this attribute to (apparently in MOLE it was supposed to be the function code of the point mine symbol, but I don't know how an end-user might have understood this). 

A simpler solution (and possible after the redundant entries are removed) is to include the mine type as an entity subtype:

2707**01** Minefield : LAND MINE
2707**02** Minefield : ANTIPERSONNEL LAND MINE
etc.

Alternately, if the plan is to add/start using the SIDC Modifier 1 & 2 fields for Control Measure (appendix H) symbols - it would be possible to capture the "mine type" there. Either approach would be more consistent, less error-prone, and easier for end users. 

Some last thoughts:

1. I was actually fine with how the Minefield symbol was specified as is (it is similar/consistent with how other control measure graphics that include point graphics are specified - for example Moving Convoy)  - the only clarification that I think it required was indicating that there could be multiple mine point graphics included in the area ex. "[A]...[An]" and adding a few more examples to show this.
2. Listing/confirming what the mine types actually are in 2525D
    1. 2525D Mine Types: LAND MINE, ANTIPERSONNEL LAND MINE, ANTITANK MINE, 
IMPROVISED EXPLOSIVE DEVICE (IED), LESS THAN LETHAL 
3. Noting the difference between the point mine types in 2525C and 2525D so may be a 2525C<->D interoperability issue (and possibly a legacy doctrine issue)
    1. 2525C Mine Types: UNSPECIFIED MINE, ANTITANK, ANTITANK ANTIHANDLING, ANTIHANDLING ANTITANK, ANTITANK DIRECTIONAL, DIRECTIONAL ANTITANK, ANTIPERSONNEL, WIDE AREA MINES
4. Linking to the [where we discussed this before](https://github.com/Esri/military-features-data/issues/39#issuecomment-103200728) (since I had a hard time finding)

**Comment by ottenw** [comment]
@csmoore Great input, thank you!  With what I was proposing, I had not considered that a minefield symbol could not be rendered by the SIDC alone.  Control measure symbols will start using sector 1 modifiers when the change I drafted to fix issues with the Limited Access Area (LAA) is submitted to SSMC meeting next month and approved; @abouffard and @joebayles are aware of this.  For the minefields, doctrinally any minefield can contain between one and three mine types.  I will update the minefield change proposal to remove the proposed new Mine Type amplifier and instead define the mine type contents with new sector 1 modifiers so minefields can be rendered by an SIDC alone.  WRT the Redundant Dummies, in the same CP I will propose deleting all SIDCs in appendix H that include a Dummy; delete amplifier AB from MIL-STD-2525D; expand MIL-STD-2525D base document description of the Dummy portion of SIDC set A position 8 "HQ / Task Force / Dummy, to include descriptions/pictures on how to render the Dummy indicator, and add some additional text about Dummies into appendix H.

**Comment by joebayles** [comment]
:+1:

**Comment by ottenw** [comment]
Issues resolved via approved symbology change proposals at SSMC 2016-1.

**Comment by joebayles** [comment]
@abouffard should we keep this open until the changes are incorporated into JMSML?

**Comment by abouffard** [comment]
We should probably open a new issue using the same format I established with other CPs, like https://github.com/Esri/joint-military-symbology-xml/issues/191

We should really do that with every approved CP, so we can track each one and its eventual implementation in JMSML.
