### ISSUE TITLE
Minimum Safe Distance Symbol Issues

### ISSUE THREAD

**Issue by joebayles** [Esri/joint-military-symbology-xml#240]
After discussing the issues rendering Minimum Safe Distance Zone (25272100), I believe a CP should be drafted to bring clarity to this symbol. Understand that the design and intent behind this symbol is to render two concentric circles around a fixed point denoting minimum safe distance of a CBRN nature. These safe distances should not be confused with Fires control measures (i.e. for indirect fire and air to ground engagements). The implication from the Orientation guidance is that it is more like CBRN safety zones, like this guidance from the EPA: http://www2.epa.gov/emergency-response/safety-zones.

>1. The exclusion zone (or hot zone) is the area with actual or potential contamination and the highest potential for exposure to hazardous substances.
2. The contamination reduction zone (or warm zone) is the transition area between the exclusion and support zones. This area is where responders enter and exit the exclusion zone and where decontamination activities take place.
3. The support zone (or cold zone) is the area of the site that is free from contamination and that may be safely used as a planning and staging area.

The implication (especially with the removal of the 3rd ring in https://github.com/Esri/joint-military-symbology-xml/issues/190), is that the inside of circle 1 is the Hot Zone, the inside of circle 2 is the Warm Zone, and anything outside of circle 2 is the Cold Zone.

Given all of the above, I believe the following issues need to be addressed:
1. This symbol only works if the event is at a single point. If the event is an area (which it most definitely will be, and therefore rendered with the Contaminated Area symbols (25271700-25272001), the area of the contaminated area could possibly fall outside of the circles completely, for example:
![image](https://cloud.githubusercontent.com/assets/5016557/11071547/353c7dd4-8796-11e5-8ecd-43a0bd4c90d4.png)
2. There is no mention of how the radii are identified or communicated, except "As defined by operator".
3. The Note in the Draw Rules is counterintuitive for the rest of the symbol explanation. That guidance would be better suited for a symbol developed for Minimum Safe Distances and Risk Estimate Distances, tools developed for indirect fire planning. I will create another issue for these.

I suggest that a CBRN-type command (MSCoE CDID?) be asked for clarification and:
1. The draw rules be changed to reflect that this basically renders two polygons around the event (point or area), offset by the distances identified based on the type of event. This could possibly create more than one symbol, since Contaminated Areas are currently seven separate symbols).
2. The Note in the Draw Rules be removed.
3. The symbol be renamed something that deconflicts it from Indirect Fire Minimum Safe Distances (Safe Zones)?

@ottenw, please weigh in.

https://github.com/Esri/joint-military-symbology-xml/issues/190
https://github.com/Esri/military-features-data/issues/166

**Comment by ottenw** [comment]
@joebayles This is a CBRN symbol.  The doctrinal reference / requirement source for this symbol is FM 3-11.3 / MCRP 3-37.2A / NTTP 3-11.25 / AFTTP(I) 3-2.56 "MULTISERVICE TACTICS, TECHNIQUES, AND PROCEDURES FOR CHEMICAL, BIOLOGICAL, RADIOLOGICAL, AND NUCLEAR CONTAMINATION AVOIDANCE".  This symbol is described on page I-3 "Figure I-1. STRIKWARN Plot Showing MSD 1 and MSD 2, Single-Burst"; I included this figure and the NATO one in the CP that removed the doctrinally incorrect third ring.  Note this symbol is specifically for a Single Burst.  The symbol for Multiple Bursts, is on page I-4 of the same document , "Figure I-2. STRIKWARN Plot Showing Multiple Bursts".  The multiple burst symbol is not supported in MIL-STD-2525.

WRT issue # "2. There is no mention of how the radii are identified or communicated, except "As defined by operator".  This for automated systems, this symbol is rendered upon the receipt of a Strike Warning (StrikWarn) message; USMTF, VMF, ADat-P3, ABCS xml schema instance, etc.  The purpose of this message is "To transmit information needed for friendly forces to take safety precautions against the blast effects of friendly conventional and nuclear bursts".  The message provides the data required to render the symbol - center point and two distances, one for each radii.  If contamination is detected after the burst then a separate action would generate one or more contaminated areas.

Fire Support C2 systems when planning fires often use a collateral damage assessment tool (most are classified) which uses  a variety of inputs, to include point of impact, trajectory, munitions specific effects data, elevation data, and vegetation and man made features.  Of the outputs I have seen, none have been circular.  

Agree a CP is needed to clarify draw rules; I'll draft one.  Since we are past the CP cut off date for new CPs to be included in 2525D Ch1, I'll do this as a modification to the approved CP.  Your thoughts?

**Comment by joebayles** [comment]
Thanks for the clarification @ottenw. 

Re: STRIKWARN, understood. In this instance, I think we're good as long as the draw rules are up-to-date. Now, I understand the STRIKWARN will carry two numbers (in hundreds of meters), which is the radii of each MSD.

@abouffard, @csmoore, @Dbarnes1 , we need to ensure that we build those two attributes into our schema to receive the message properly.

Re: MSDs/REDs, understood. I am operating off of a pencil-and-paper, maneuver-planning understanding of Fire Support. Would we still want to standardize that symbology? Seems useful to me. Let's make sure to divest this part of the conversation from this issue and keep it focused on STRIKWARN MSDs. I'll copy your comment here: https://github.com/Esri/joint-military-symbology-xml/issues/241

**Comment by csmoore** [comment]
@joebayles - what [two attributes](https://github.com/Esri/joint-military-symbology-xml/issues/240#issuecomment-155577760)? if you mean radius1, radius2 - these are already defined [by the points](https://cloud.githubusercontent.com/assets/3090809/11071184/698b25ce-87ad-11e5-9698-48a64fefa5cf.png)

**Comment by ottenw** [comment]
@joebayles @abouffard - please see attached draft / proposed change one to the CP.  Your thoughts?
[15-029C01-AR Correction to Minimum Safe Distance Control Measure Symbol.docx](https://github.com/Esri/joint-military-symbology-xml/files/38303/15-029C01-AR.Correction.to.Minimum.Safe.Distance.Control.Measure.Symbol.docx)

**Comment by joebayles** [comment]
@ottenw :+1:

**Comment by joebayles** [comment]
My question was answered. Closing this issue.
