### ISSUE TITLE
Missing 2525C legacy SVGs need to be created and readme on process added to folder

### ISSUE THREAD

**Issue by abouffard** [Esri/joint-military-symbology-xml#254]
@csmoore , @Dbarnes1 ,

The following full frame retired legacy symbol SVG files need to be created and placed in this folder, to round out retired symbology support in the legacy stylx.:

https://github.com/Esri/joint-military-symbology-xml/tree/master/svg/MIL_STD_2525D_Symbols/Legacy/2525C

S-G-UCAWWR
S-G-UCDC--
S-G-UCDSC-
S-G-UCDSS-
S-G-UCDSV-
S-G-UCDMLA
S-G-UCDHH-
S-G-UCDHP-
S-G-UCFHX-
S-G-UCFML-
E-O-BJ----

For each of the above cases there should be four frame shape specific svg files created and the file names should start with the above strings and then have _0.svg, _1.svg, _2.svg, and _3.svg appended.

So for the first one above:

S-G-UCAWWR_0.svg = Unknown/Pending version
S-G-UCAWWR_1.svg = Friend/Assumed Friend version
S-G-UCAWWR_2.svg = Neutral version
S-G-UCAWWR_3.svg = Hostile/Suspect version

Follow the SVG creation procedure documented here:

https://esri.app.box.com/files/0/f/6069861186/1/f_49357339478

UPDATE CSM: Please also convert the readme "README-RetiredSymbolsToDeltaProces.doc" to a markdown readme and include in the `svg/MIL_STD_2525D_Symbols/Legacy/2525C` and include in the same PR.

**Comment by csmoore** [comment]
Assigned to @Dbarnes1 since he is working on this sprint. 

I also added a subtask to this (to the title and original comment) to convert the process readme: "README-RetiredSymbolsToDeltaProces.doc" to a markdown readme and include in the same folder with the legacy SVGs(`svg/MIL_STD_2525D_Symbols/Legacy/2525C`) so this document can be more easily found with the maintained SVGs and after the project ends.

**Comment by csmoore** [comment]
@abouffard @Dbarnes1 for the `E-O-BJ----` case above - I was thinking this would not require a new legacy SVG because this just uses 2 existing icons. Cases like this is what the `ExtraIcon` column was intended to address and here is how I created this:

![image](https://cloud.githubusercontent.com/assets/3090809/13603935/7f090916-e50e-11e5-8b1e-5801b9f18c34.png)

![image](https://cloud.githubusercontent.com/assets/3090809/13604047/e6bf7644-e50e-11e5-9aa1-d180feb05a72.png)

Feel free to continue with the planned approach, I just wanted to let you know that this option is available if you already have the existing icons in 2525D and just want to combine them differently.

**Comment by Dbarnes1** [comment]
I believe I've fixed these missing symbols. The following photos are using the legacy renderer. 

Here is an example for S-G-UCAWWR:

Friendly: 
![image](https://cloud.githubusercontent.com/assets/13024357/13618007/8cafd036-e536-11e5-9245-602cc5f8f37e.png)

Neutral:
![image](https://cloud.githubusercontent.com/assets/13024357/13618023/a1f37b5a-e536-11e5-866d-fdbe61d40b73.png)

Unknown:
![image](https://cloud.githubusercontent.com/assets/13024357/13618074/f34e3382-e536-11e5-80b9-f0b849dd1154.png)

Hostile:
![image](https://cloud.githubusercontent.com/assets/13024357/13618085/0589e83e-e537-11e5-871d-8e85f09cfc5d.png)




I'll include the created svgs and the new mil2525d_to_legacy renderer in coming pull requests.

**Comment by csmoore** [comment]
I tested and the one above(S-G-UCAWWR) looks OK (although I now notice all of the retired ones have thicker lines than 2525D uses), the other icons seem a bit over-large for(or touching) the frame (but this is minor unless @abouffard disagrees when he tests) :

![image](https://cloud.githubusercontent.com/assets/3090809/13637621/40db90e6-e5d6-11e5-8377-ef9f8ec87a19.png)

This one, however, still does not look correct (team echelon indicator should be above the frame like my screenshot of this above):

![image](https://cloud.githubusercontent.com/assets/3090809/13637488/9884e7f8-e5d5-11e5-82bf-719175b02fb6.png)

**Comment by Dbarnes1** [comment]
@csmoore good catch with the E-O-BJ symbol. Will there be missing mil2525BC2 symbols that need to be created? If so, I could fix this error when working on those. Let me know what you think.

**Comment by csmoore** [comment]
@Dbarnes1 - waiting to fix with the next batch is always fine, so long as it is tracked somewhere. 

Maybe time to discuss where/how to better track these major-minor legacy issues now that things have migrated here. I was using that interim/informal spreadsheet - "Corrections_To_JMSML_Produced_Mapping_C_to_D.xlsx" ( @abouffard - just a reminder that many of the items mentioned there, ex. repeated entries for SIDCs, like S-A-WM----, are still issues) - but we can start adding issues here if there is agreement

**Comment by Dbarnes1** [comment]
If it makes sense to you guys, I'd rather have the issues on github than in a spreadsheet.

**Comment by abouffard** [comment]
I'd prefer tracking them in GitHub

**Comment by Dbarnes1** [comment]
https://github.com/Esri/joint-military-symbology-xml/issues/258 link to new issue for remaining SVG issues/questions.

**Comment by csmoore** [comment]
There seems to be some confusion/disagreement whether this issue is fixed/complete ( @abouffard isn't sure if fixed, but I do see a commit that appears to address these here: https://github.com/Esri/joint-military-symbology-xml/commit/e201148e91825b321176bde5e91219436ff2331b ).

Just to get this wrapped up/checked - assigning this to @abouffard to verify. 

As part of verification, please add a check/task box to the original issue to indicate if fixed. If there are still just a few bad ones after testing (like the bad echelon placement on E-O-BJ---- mentioned in this thread) perhaps just move to #258 and close this issue.

**Comment by abouffard** [comment]
Verified that all of the above SVGs were created and are in master.  Moving E-O-BJ---- to #258.

**Comment by conklinbd** [comment]
@abouffard I didn't actually assign this. It must have been something in Waffle that automatically did it for me.

**Comment by abouffard** [comment]
Thanks @conklinbd
