### ISSUE TITLE
Style Items Table should use human readable names in Name Field not SIDCs or Hierarchy Code

### ISSUE THREAD

**Issue by csmoore** [Esri/joint-military-symbology-xml#292]
Noticed that the Name field for the many entries is using the SIDC or Hierarchy Code rather than a human readable name. Ex:

https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/legacy_support/All_ID_Mapping_Original.csv#L751 

`Symbols_Root}\Legacy\2525C\I-U-SRU---.emf,64,`**I-U-SRU---**

https://raw.githubusercontent.com/Esri/joint-military-symbology-xml/master/samples/imagefile_name_category_tags/Military-All-Icons.csv

Because this is the name a user will see in both the Pro style manager and more importantly the Pro symbol editor these should be changed to human-readable names (Note: the key field should likely remain the SIDC)

(Note: Updated original description to include Style Items)

**Comment by abouffard** [comment]
I chose to use the hierarchy codes from 2525C for the legacy entities because they weren't being captured elsewhere and for legacy SVGs we had to build they are the closest equivalent in the older standards to the colon separated names we normally use for 2525D.  We derive the 2525D names from the formal entity/entity type/entity subtype hierarchy strings, which don't exist in the older standards.

2525C and 2525BC2 symbols that map to 2525D symbols use the 2525D colon separated symbol names.  2525C and 2525BC2 symbols that have to be represented by legacy SVGs, because they look different from their 2525D equivalent, or don't have a 2525D equivalent, currently use the dot separated hierarchy string as their name.

If we want to use more human readable text for the legacy entities/SVGs in the lookup, we'll need to either:

1. Use the closest name we can from 2525D for those symbols which are a close match to a 2525D symbol = less work.
2. Add more accurate names to JMSML for those legacy entities to reflect what they are actually called in 2525C = more work.

**Comment by csmoore** [comment]
If this name is only used in this table I'm inclined not to worry about, but if this is the name the user will see in the style and elsewhere (like the ProSymbolEditor) then we should change and come up with a better naming convention (but certainly keep this as a tag).

I haven't yet looked at that style entries and tags to see if they are complete...i.e. able to completely create user-friendly symbols from the ProSymbolEditor when this supports legacy so I should do this now...

**Comment by csmoore** [comment]
Looks like the legacy name is the SIDC - that probably won't work either (though that should be the Key which is correct)

Also - why is there a fill in the icons - is this a global issue? ( @abouffard  @Dbarnes1 ) - 

![image](https://cloud.githubusercontent.com/assets/3090809/14864421/d4da9788-0c87-11e6-8de6-146dc39e7034.png)

**Comment by abouffard** [comment]
The legacy symbol name is the SIDC because when you create a stylx from a style its the symbol's name that gets copied to the symbol's key field by Pro, where we need the SIDC.  If we use a different string for the symbol name then we'll have to use SQL code in a script to update the key field values.  I was trying to avoid that, but it may be unavoidable.

I certainly don't expect users to look inside the two mapping tables and I had largely hoped that, with the advent of an easier to use symbol editor that eventually supports all the versions of 2525, they would seldom need to look at the symbols in the style itself.

Yes, @Dbarnes1 and I are both aware of the color fill in those symbols and its on Daniel's list to fix in the SVGs.

**Comment by csmoore** [comment]
Since the easier-to-use [symbol editor](https://github.com/Esri/military-symbol-editor-addin-wpf) actually presents this name to the user, the style item name is indeed important, see image at: https://github.com/Esri/military-symbol-editor-addin-wpf#military-symbol-editor-addin-wpf - Let's work on a naming convention that makes sense & once the style is stable we can add this task/work/fix to the sprint.

The mapping table name is less important (and you are right the end-user will never see this) - but is there any reason they can't both use the same simpler name as the style item?

**Comment by csmoore** [comment]
Updated the title and original issue to include the style items - it is labeled enhancement but really something more than that in that it is a usability issue so after the 2525C style symbols problems are fixed this will likely be the next desired fix this sprint

**Comment by abouffard** [comment]
@csmoore  - here is my suggestion for a naming convention.  Basically it is to use the closest equivalent to the names we have already.

WAR.SOFUNT.AVN.ROT, the current name for S-F-AH----, could instead be:

"Movement and Maneuver : Army Aviation/Aviation Rotary Wing : Special Operations Forces (SOF)"

This is the closest combination of 2525D symbol name and 2525D modifier name used together to make the symbol.  I would recommend this approach because these names are easily derived from what's already in JMSML so requiring very little new data entry.

I don't think we want to further identify the legacy symbols by putting the version of standard they are in in the name itself, because I'd think the tags are a better place to put that information,

**Comment by csmoore** [comment]
That example looks better & more human readable to me - so long as:

1. it remains unique and won't be the same as any of the existing 2525D ones.
2. the 2525C domains use the same names  
3. anything else we have forgotten since we last did this >2+ years ago (I remember it took numerous passes/iterations to get this all correct that time)

Once you do have the name and tags ready to review we do want you to create a brief writeup that steps us through the scenario of how the (1) symbol editor will use this name & style preview to do the things it does now (identify the target layer/symbol set, available fields, etc.) (2) how to create 2525C domains using these name.

**Comment by joebayles** [comment]
@abouffard can you update this issue?

**Comment by csmoore** [comment]
I believe this is resolved - I don't think I've seen any SIDCs in the symbol names for the released mil2525c_b2 style
