### ISSUE TITLE
MIL-STD-2525D Issues

### ISSUE THREAD

**Issue by joebayles** [Esri/joint-military-symbology-xml#39]
This issue is to track issues found in the draft of MIL-STD-2525D for @abouffard to take back to the committee (@mepler). Some of these may not be issues at all, but in the review they seemed counter-intuitive, so I am listing them here.

|Location|Page|Issue|
|:---------|------:|:--------------------------|
|A-XIX|57|Acquisition is mispelled (130302)|
|A-XIX|58|Equipped is mispelled (140105)|
|A-XXV|72|Mine is not capitalized (210200)|
|A-XLIV|122|General is not capitalized (29)|
|D-II|165|Field AR (Special Designator) should have a designated location|
|F-II|328|Sea Subsurface does not have all of the Sea amplifiers (i.e. Speed, Location)|
|G-II|354|Offset Location Indicator is Field S, not Q|
|D-XIII|272|Law Enforcement (20112100) should list an Icon Type.|
|D-XIII|274|Emergency Operation (20112200) should list an Icon Type.|
|D-XIII|277|Economic Infrastructure Asset (20120204) should be Icon Type: Main|
|D-XV|294|Symbol Set Code should be 20|
|D-XV|294|Descriptions should only be listed once|
|D-XV|294|All modifiers should have a Category|
|I-II|737|Shoreline Protection - EntitySubType and EntitySubSubType?|
|I-II|738|Hydrography:Aids to Navigation - Error! Bookmark not defined.|

**Comment by joebayles** [comment]
@abouffard ensuring that these are still an issue and creating a CP.

**Comment by abouffard** [comment]
Above errors have been reviewed, in light of the June 10th final pdf version of 2525D, and a new change proposal has been authored and submitted, recommending these errors be fixed in 2525D Change 1.

https://github.com/Esri/joint-military-symbology-xml/blob/master/documentation/change_proposals/CP_Esri_022415-1.doc added in #173 

@joebayles , I recommend we close this issue and continue tracking these errors via the CP process.

**Comment by joebayles** [comment]
Verified.
